logging:
  level:
    io:
      eventuate: DEBUG

spring:
  datasource:
    url: jdbc:mysql://${DOCKER_HOST_IP:localhost}/eventuate
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.jdbc.Driver

eventuatelocal:
  kafka:
    bootstrap:
      servers: ${DOCKER_HOST_IP:localhost}:9092
  zookeeper:
    connection:
      string: ${DOCKER_HOST_IP:localhost}:2181

activemq:
  url: tcp://${DOCKER_HOST_IP:localhost}:61616

rabbitmq:
  url: ${DOCKER_HOST_IP:localhost}

---
spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://${DOCKER_HOST_IP:localhost}/eventuate
    username: eventuate
    password: eventuate
    driver-class-name: org.postgresql.Driver

